#!/usr/bin/env python3
"""codex_image.py — deterministic image generation through Codex's built-in tool.

Drives `codex exec` non-interactively so the model uses its BUILT-IN image
generation tool (image_gen) via the ChatGPT subscription quota.
No OPENAI_API_KEY, no API billing.

Why a script instead of calling codex by hand:
  - Forces the real tool every time (a fixed contract header the model can't skip).
  - Pipes the prompt via stdin, so long multi-line Chinese prompts never hit
    Git Bash / argv escaping bugs.
  - Locates the generated PNG by THIS run's codex SESSION ID
    ($CODEX_HOME/generated_images/<session_id>/ig_*.png) — robust even when
    another codex session (a sibling Claude Code project, the desktop app, etc.)
    is generating images at the same time. Relying on "the newest image in
    generated_images" (what the model itself does) steals other sessions' images.
  - Validates the result is a real raster PNG (parses the IHDR header, no Pillow
    dependency) and reports width/height so a code-drawn fake is caught.
  - A best-effort lockfile serializes runs as a courtesy to sibling sessions that
    still rely on "newest"; correctness no longer depends on it.

Usage:
  echo "<structured prompt>" | python codex_image.py --out hero.png
  python codex_image.py --out hero.png --prompt-file prompt.txt --size "1536x1024"
  python codex_image.py --out cutout.png --prompt-file p.txt --transparent
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

CONTRACT_HEADER = """You are running in non-interactive automation. Your only job is to create a raster image using your BUILT-IN image generation tool (image_gen), which runs on the ChatGPT subscription.

HARD RULES (a violation is a total failure):
- You MUST call the built-in image generation tool to produce real pixels.
- NEVER draw, fake, or synthesize the image with code, PowerShell, Python, System.Drawing, ImageMagick, matplotlib, SVG, HTML, or canvas. Only the built-in tool may create the image.
- Do NOT ask questions. Do NOT explain your steps. Work autonomously until the image exists.
- Produce exactly ONE image unless the request explicitly asks for variants.
"""

OUTPUT_FOOTER = """SAVE TARGET:
The built-in tool auto-saves under $CODEX_HOME/generated_images/<session>/. After it finishes, COPY the final image to this exact absolute path (create parent folders if needed), and leave the original in place:
{out}
Your final message must be only that saved path and nothing else."""

TRANSPARENT_BLOCK = """TRANSPARENT-BACKGROUND MODE:
Render the subject on a perfectly flat solid #00ff00 chroma-key background for later background removal.
- The background must be one uniform #00ff00 with no shadow, gradient, texture, reflection, floor plane, or lighting spill.
- Do not use #00ff00 anywhere in the subject itself.
- Keep the subject fully separated with crisp edges and generous padding. No cast shadow, no contact shadow, no watermark, no text unless explicitly requested."""


def codex_home() -> Path:
    env = os.environ.get("CODEX_HOME")
    return Path(env) if env else Path.home() / ".codex"


def generated_images_dir() -> Path:
    return codex_home() / "generated_images"


# ----------------------------------------------------------------------------- locate via session id

def find_my_session_id(workdir: str, start_ts: float):
    """Find the codex session this run started, by matching the rollout whose
    session_meta cwd == our workdir and which was written during our run. The
    session id is also the name of the generated_images subdir."""
    sessions = codex_home() / "sessions"
    if not sessions.exists():
        return None
    target = os.path.normcase(os.path.abspath(workdir))
    best = None  # (mtime, sid)
    for p in sessions.rglob("rollout-*.jsonl"):
        try:
            if p.stat().st_mtime < start_ts - 5:
                continue
            with open(p, encoding="utf-8", errors="replace") as f:
                first = f.readline()
        except OSError:
            continue
        try:
            meta = json.loads(first)
        except Exception:  # noqa: BLE001
            continue
        payload = meta.get("payload", meta) if isinstance(meta, dict) else {}
        cwd = (payload or {}).get("cwd")
        sid = (payload or {}).get("session_id") or (payload or {}).get("id")
        if not cwd or not sid:
            continue
        if os.path.normcase(os.path.abspath(cwd)) == target:
            mt = p.stat().st_mtime
            if best is None or mt > best[0]:
                best = (mt, sid)
    return best[1] if best else None


def image_for_session(sid: str):
    """Newest PNG generated by a specific codex session."""
    d = generated_images_dir() / sid
    if not d.exists():
        return None
    pngs = sorted(d.glob("*.png"), key=lambda x: x.stat().st_mtime, reverse=True)
    return pngs[0] if pngs else None


def newest_new_png(root: Path, before: dict, start_ts: float):
    """Fallback only: newest png that did not exist before the run."""
    if not root.exists():
        return None
    candidates = []
    for p in root.rglob("*.png"):
        try:
            mtime = p.stat().st_mtime
        except OSError:
            continue
        if str(p) not in before or mtime >= start_ts - 5:
            candidates.append((mtime, p))
    if not candidates:
        return None
    candidates.sort(reverse=True)
    return candidates[0][1]


def snapshot_pngs(root: Path):
    seen = {}
    if not root.exists():
        return seen
    for p in root.rglob("*.png"):
        try:
            seen[str(p)] = p.stat().st_mtime
        except OSError:
            continue
    return seen


# ----------------------------------------------------------------------------- lock (courtesy serializer)

def acquire_lock(wait_timeout: int, stale_after: int):
    """Best-effort cross-process lock. Sibling sessions that still copy "the
    newest image" must not generate at the same time as us, or they would grab
    each other's output. We locate by session id regardless, so this is courtesy,
    not correctness. Steals a lock older than stale_after (crashed holder)."""
    lock_path = codex_home() / ".codex_image.lock"
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    start = time.time()
    while True:
        try:
            fd = os.open(str(lock_path), os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            os.write(fd, str(os.getpid()).encode())
            os.close(fd)
            return lock_path
        except FileExistsError:
            try:
                if time.time() - lock_path.stat().st_mtime > stale_after:
                    lock_path.unlink()
                    continue
            except OSError:
                pass
            if time.time() - start > wait_timeout:
                return None  # give up on the lock; session-id locate still works
            time.sleep(1.5)


def release_lock(lock_path):
    if not lock_path:
        return
    try:
        lock_path.unlink()
    except OSError:
        pass


# ----------------------------------------------------------------------------- png + codex

def png_size(path: Path):
    """(width, height) for a valid PNG, else None. No external deps."""
    try:
        with open(path, "rb") as f:
            head = f.read(24)
    except OSError:
        return None
    if len(head) < 24 or head[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    return int.from_bytes(head[16:20], "big"), int.from_bytes(head[20:24], "big")


def build_prompt(body: str, size: str, transparent: bool, out_abs: str) -> str:
    parts = [CONTRACT_HEADER.strip(), "", "REQUEST:", body.strip()]
    if size:
        parts += [
            "",
            f"TARGET ASPECT / FRAMING: {size}. Steer the built-in tool toward this aspect ratio. "
            "(The built-in tool fixes the final resolution itself at ~1.5MP; it cannot do true 4K.)",
        ]
    if transparent:
        parts += ["", TRANSPARENT_BLOCK.strip()]
    parts += ["", OUTPUT_FOOTER.format(out=out_abs)]
    return "\n".join(parts)


def resolve_codex():
    """Locate the codex binary; prefer a real .exe so subprocess runs it without a
    shell (on Windows `codex` on PATH is an npm .cmd shim CreateProcess can't run).
    Returns (argv_prefix, use_shell)."""
    for env in ("CODEX_BIN", "CODEX_CLI_PATH"):
        val = os.environ.get(env)
        if val and Path(val).exists():
            return [val], False
    base = Path.home() / "AppData" / "Local" / "OpenAI" / "Codex" / "bin"
    exes = sorted(base.glob("*/codex.exe"), key=lambda p: p.stat().st_mtime, reverse=True)
    if exes:
        return [str(exes[0])], False
    found = shutil.which("codex.exe")
    if found:
        return [found], False
    found = shutil.which("codex") or shutil.which("codex.cmd")
    if found:
        return [found], not found.lower().endswith(".exe")
    return ["codex"], False


def run_codex(prompt: str, workdir: str, model: str, timeout: int):
    prefix, use_shell = resolve_codex()
    argv = prefix + ["exec", "--skip-git-repo-check", "--sandbox", "workspace-write", "-C", workdir]
    if model:
        argv += ["-m", model]
    argv += ["-"]  # read prompt from stdin
    try:
        target = subprocess.list2cmdline(argv) if use_shell else argv
        proc = subprocess.run(
            target, input=prompt, capture_output=True, text=True,
            encoding="utf-8", errors="replace", timeout=timeout, shell=use_shell,
        )
        return proc.returncode, proc.stdout or "", proc.stderr or ""
    except FileNotFoundError:
        return 127, "", "codex CLI not found. Set CODEX_BIN, install codex, or run `codex login`."
    except subprocess.TimeoutExpired:
        return 124, "", f"codex exec timed out after {timeout}s."


def remove_chroma_key(src: Path, out: Path):
    helper = codex_home() / "skills" / ".system" / "imagegen" / "scripts" / "remove_chroma_key.py"
    if not helper.exists():
        return False, f"chroma-key helper not found at {helper}"
    cmd = [
        sys.executable, str(helper), "--input", str(src), "--out", str(out),
        "--auto-key", "border", "--soft-matte",
        "--transparent-threshold", "12", "--opaque-threshold", "220", "--despill",
    ]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    except Exception as exc:  # noqa: BLE001
        return False, f"chroma-key helper failed to launch: {exc}"
    if proc.returncode != 0:
        tail = (proc.stderr or proc.stdout or "").strip()[-400:]
        return False, f"chroma-key helper exit {proc.returncode}: {tail} (needs Pillow: pip install pillow)"
    return True, "ok"


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate an image via Codex's built-in tool (subscription quota).")
    ap.add_argument("--out", required=True, help="Output PNG path.")
    ap.add_argument("--prompt-file", help="File with the prompt body. If omitted, read stdin.")
    ap.add_argument("--workdir", help="Codex working root. Default: the output file's folder.")
    ap.add_argument("--size", default="", help='Aspect/size hint, e.g. "1536x1024", "portrait 2:3". Steers ratio only; resolution is ~1.5MP regardless.')
    ap.add_argument("--transparent", action="store_true", help="Chroma-key workflow -> transparent PNG.")
    ap.add_argument("--model", default="", help="Override codex model.")
    ap.add_argument("--timeout", type=int, default=300, help="Per-run codex timeout seconds (default 300).")
    ap.add_argument("--lock-wait", type=int, default=1800, help="Max seconds to wait for the courtesy lock.")
    ap.add_argument("--print-prompt", action="store_true", help="Print the final prompt and exit.")
    args = ap.parse_args()

    body = (Path(args.prompt_file).read_text(encoding="utf-8") if args.prompt_file else sys.stdin.read()).strip()
    if not body:
        print(json.dumps({"ok": False, "error": "empty prompt body"}, ensure_ascii=False))
        return 2

    out = Path(args.out).expanduser().resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    workdir = str(Path(args.workdir).resolve()) if args.workdir else str(out.parent)
    Path(workdir).mkdir(parents=True, exist_ok=True)

    codex_target = out if not args.transparent else out.with_name(out.stem + "_chroma_src.png")
    final_prompt = build_prompt(body, args.size, args.transparent, str(codex_target))
    if args.print_prompt:
        print(final_prompt)
        return 0

    gen_dir = generated_images_dir()
    lock = acquire_lock(wait_timeout=args.lock_wait, stale_after=max(args.timeout + 180, 480))
    try:
        before = snapshot_pngs(gen_dir)
        start_ts = time.time()
        rc, stdout, stderr = run_codex(final_prompt, workdir, args.model, args.timeout)

        # Locate THIS run's image. Session id first (concurrency-safe), then fallbacks.
        source, picked = None, None
        sid = find_my_session_id(workdir, start_ts)
        if sid:
            picked = image_for_session(sid)
            if picked:
                source = "session:" + sid[:8]
        if source is None and codex_target.exists() and codex_target.stat().st_mtime >= start_ts - 5:
            source = "codex-direct"
        if source is None:
            picked = newest_new_png(gen_dir, before, start_ts)
            if picked:
                source = "newest-fallback"
        if picked is not None and source != "codex-direct":
            shutil.copy2(picked, codex_target)
    finally:
        release_lock(lock)

    result = {"ok": False, "out": str(out), "source": source,
              "codex_returncode": rc, "transparent": args.transparent}

    if source is None:
        result["error"] = "no generated image found"
        result["codex_stderr_tail"] = stderr.strip()[-600:]
        result["codex_stdout_tail"] = stdout.strip()[-600:]
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 1

    if args.transparent:
        ok, msg = remove_chroma_key(codex_target, out)
        result["chroma_key"] = msg
        if not ok:
            result["error"] = "chroma-key removal failed; opaque source kept at " + str(codex_target)
            print(json.dumps(result, ensure_ascii=False, indent=2))
            return 1

    dims = png_size(out)
    if dims is None:
        result["error"] = "output is not a valid PNG (model may have drawn with code)"
        result["bytes"] = out.stat().st_size if out.exists() else 0
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 1

    result.update(ok=True, width=dims[0], height=dims[1], bytes=out.stat().st_size,
                  final_message=stdout.strip()[-200:])
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
